# Create a separate workflow file (e.g., terraform-destroy.yml) for the destroy operation
name: Terraform Destroy

on:
  workflow_dispatch: # Allows you to trigger the workflow manually

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.BUCKET_TF_STATE }}" -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Plan (Destroy)
        run: terraform plan -destroy -out=tfplan

      - name: Terraform Apply (Destroy)
        run: terraform apply -auto-approve tfplan
