# Create a separate workflow file (e.g., terraform-destroy.yml) for the destroy operation
name: Terraform Destroy

on:
  workflow_dispatch: # Allows you to trigger the workflow manually

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-north-1
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.BUCKET_TF_STATE }}" -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Plan (Destroy)
        run: terraform plan -destroy -out=tfplan -var "eks_admin_role_arn=arn:aws:iam::891377190847:role/eks-admin-role" -out=tfplan

      - name: Terraform Apply (Destroy)
        run: terraform apply -auto-approve tfplan
